### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by tkettle220** [tkettle220/quora-clone#20]

**Comment by s-pangburn** [comment]
Hey Tommy,

Please update your wiki with the Heroku link!

**Comment by tkettle220** [comment]
Hey,

Just updated it!  Because of how facebook auth works, I need to tell
facebook where this app should expect requests from, which for now is set
to localhost, so if you want to check out the facebook login/signup just
let me know to switch the setting for you.

Thanks!
Tommy

**Comment by s-pangburn** [comment]
Okay, sounds good! Great job on the styling, your app is looking great!

### Things to fix

1. Your errors should either display in red text above the login form or the bar at the top should be styled to stand out more (i.e. white text on a red background or something similar)

2. This is a small thing, but your "Login" button should probably highlight on hover, since your demo login and facebook login buttons already do that. Just makes the site feel more unified. Same with "Forgot Password?"

3. Maybe round the corners on the form a little bit.

4. As we discussed, make sure you can login both with the Facebook button and the sign in form!

5. Style the forgot password and create password dialog pages, as well as the navbar once you're logged in.

Once these are finished, I'll mark this feature as complete. Good luck!

**Comment by tkettle220** [comment]
1.Errors now display a bit nicer, and don't create a white bar at the top
when there are no errors.

2.I'm going to leave the login button unhighlighted for now, just to stick
to as close a copy to the actual Quora site for now and then maybe go back
and make customizations like that if that's alright with you.  I did change
the "Forgot Password?" though, to have a hover effect.

3. Done

4. You can do both logins now.  The confirmation email now gives a link to
optionally set a password if you created an account through facebook.

5. Styled!

Thanks!

**Comment by s-pangburn** [comment]
Looks good! I'm going to mark this as complete. Well done, it's looking great!

**Comment by s-pangburn** [comment]
Oh, and yeah, don't worry about the login button thing. It's a minor detail, and if you want to be more faithful to the Quora site, that's totally up to your discretion.
